export const site = {
  brand: 'ΜΑΡΓΑΡΩΝΗΣ',
  brandFull: 'Μαργαρώνης Service',
  tagline: 'Συνεργείο Αυτοκινήτων',
  phoneDisplay: '22410 74605',
  phoneHref: 'tel:+302241074605',
  addressStreet: 'Ι. Καποδιστρίου 44',
  addressCity: 'Ρόδος',
  addressPostalCode: '85100',
  addressRegion: 'Νότιο Αιγαίο',
  addressCountry: 'GR',
  addressFull: 'Ι. Καποδιστρίου 44, Ρόδος 851 00',
  mapsHref: `https://www.google.com/maps/search/?api=1&query=${encodeURIComponent('Margaronis Service, I. Kapodistriou 44, Rodos 851 00')}`,
  siteUrl: 'https://margaronis-service.gr',
  hoursWeekday: '9:00 – 17:00',
  hoursSaturday: '9:00 – 14:00',
  hoursOpenBadge: 'Ανοιχτά · Δευτ–Παρ 9:00–17:00',
} as const
